# Welcome to Jekyll!
#

# Site settings
title: Lucie Martinez
description: Étudiante en design graphique
owner: Lucie Martinez # or company name
first_published: 2016 # if migrating another site, the year of your first publish
email: tests@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://lucie-martinez.fr" # the base hostname & protocol for your site
social:
  #twitter: https://twitter.com/<username>
  github: https://github.com/<username>
  linkedin-square: https://linkedin.com/in/lucie-martinez-701b7b106?trk=hp-identity-name
  facebook-official: https://facebook.com/Lucy.mo.11
  #google-plus-square: https://plus.google.com/u/0/+<username>
  email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  pinterest: https://fr.pinterest.com/lmartinez1195/
  #stack-overflow:
  vimeo: https://vimeo.com/user41192176
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
